<?php
/**
 * ScriptsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Metatavu\Metamind
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metamind API
 *
 * Brain spec for Metamind.
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Metatavu\Metamind;

use \Metatavu\Metamind\Configuration;
use \Metatavu\Metamind\ApiException;
use \Metatavu\Metamind\ObjectSerializer;

/**
 * ScriptsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Metatavu\Metamind
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScriptsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createScript
     *
     * Posts new script.
     *
     */
    public function testCreateScript()
    {
    }
}
